name: Deploy Helm Chart
on:
  workflow_call:
    secrets:
      CLUSTER_CONFIG:
        required: true
      BASE64DOCKERAUTH:
        required: true
      APP_NAME:
        required: true
      RELEASE_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: dtzar/helm-kubectl:3.2.1
      env:
        CLUSTER_CONFIG: ${{ secrets.CLUSTER_CONFIG }}
        BASE64DOCKERAUTH: ${{ secrets.BASE64DOCKERAUTH }}
        APP_NAME: ${{ secrets.APP_NAME }}
        RELEASE_NAME: ${{ secrets.RELEASE_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kubernetes via Helm 3.2.1
        run: |
          echo ${CLUSTER_CONFIG} | base64 -d > /kubeconfig.yml
          kubectl apply -f namespace.yml --kubeconfig=/kubeconfig.yml
          cd helm
          sed -i -e "s|#BASE64DOCKERAUTH#|$BASE64DOCKERAUTH|g" templates/imagepull.yml   
          helm list --namespace ${APP_NAME} --kubeconfig=/kubeconfig.yml
          export DEPLOYS=$(helm ls --namespace ${APP_NAME} --kubeconfig=/kubeconfig.yml | grep $RELEASE_NAME | wc -l)
          echo $DEPLOYS
          if [ ${DEPLOYS} -eq 0 ]; then helm install ${RELEASE_NAME} . --kubeconfig=/kubeconfig.yml --namespace=${APP_NAME}; else helm upgrade ${RELEASE_NAME} . --kubeconfig=/kubeconfig.yml --namespace=${APP_NAME}; fi
