name: Dotnet Test
on:
  workflow_call:
    inputs:
      PROJECT_PATH:
        type: string
        description: PROJECT PATH
        required: true
      DOTNET_VERSION:
        type: string
        description: DOTNET VERSION
        default: 6.1.x
        required: false      
jobs:
  dotnet-test:
    runs-on: ubuntu-20.04
    env:
      PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
      DOTNET_VERSION: ${{ inputs.DOTNET_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: Test with dotnet
        run: dotnet test ${{ env.PROJECT_PATH }} --logger trx --results-directory "TestResults-${{ env.DOTNET_VERSION  }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION  }}
          path: TestResults-${{ env.DOTNET_VERSION }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}