name: Ionic Android Build
on:
  workflow_call:
    inputs:
      CONTAINER_IMAGE:
        type: string
        description: IONIC BUILDER IMAGE
        required: true
jobs:
  ionic-android-build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.CONTAINER_IMAGE }}
    steps:
      - uses: actions/checkout@v2
      - name: Ionic Android Build
        run: |
          npm install
          java -version
          ionic cordova prepare android
          ionic cordova build android
      - uses: actions/upload-artifact@v2
        with:
          name: deploy-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
